// set context
USE ROLE OKC_MEETUP_ROLE;
USE WAREHOUSE OKC_MEETUP_WH;

// define the table
CREATE TABLE IF NOT EXISTS 
OKC_MEETUP_DB.RAW_DATASETS.AMAZON_FOOD_REVIEWS(
  ID INT,
  PRODUCT_ID STRING,
  USER_ID STRING,
  PROFILE_NAME STRING,
  HELPFULNESS_NUMERATOR INT,
  HELPFULNESS_DENOMINATOR INT,
  SCORE INT,
  TIME BIGINT,
  SUMMARY STRING,
  TEXT STRING
);